version: '3.4'

services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: WebAPI/Dockerfile
    ports:  
      - "8080:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=tfa;Username=tfa;Password=tfa;
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: tfa
      POSTGRES_USER: tfa
      POSTGRES_PASSWORD: tfa
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: